-- FaceID-KP — canonical database schema
--
-- Until now none of this existed in version control. The match_faces() function
-- is the core of the product and lived only in the Supabase dashboard, so the
-- distance operator it used could not be verified, the UNIQUE constraint the
-- TOCTOU guard depends on could not be shown to exist, and a fresh deploy
-- produced an application that crashed on the first scan.
--
-- Safe to run against an existing database: every statement is idempotent.
--
--   psql "$SUPABASE_DB_URL" -f migrations/001_init.sql
--   -- or paste into Supabase Studio -> SQL Editor

begin;

create extension if not exists vector;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
create table if not exists public.users (
    id             bigint generated by default as identity primary key,
    full_name      text        not null,
    gender         text,
    phone_number   text,
    face_embedding vector(512),
    is_deleted     boolean     not null default false,
    deleted_at     timestamptz,
    created_at     timestamptz not null default now()
);

-- Columns added after the initial release.
alter table public.users add column if not exists is_deleted     boolean not null default false;
alter table public.users add column if not exists deleted_at     timestamptz;
-- Biometric data is "data pribadi spesifik" under UU 27/2022 and requires
-- explicit, standalone consent. Recording when it was given makes the basis for
-- processing auditable.
alter table public.users add column if not exists consent_at      timestamptz;
alter table public.users add column if not exists consent_version text;

-- Case-insensitive uniqueness: "Jose", "jose" and "Jose " were previously three
-- separate members.
create unique index if not exists users_full_name_unique
    on public.users (lower(btrim(full_name)))
    where is_deleted = false;

create index if not exists users_active_idx on public.users (is_deleted);

-- ---------------------------------------------------------------------------
-- attendance_logs
-- ---------------------------------------------------------------------------
create table if not exists public.attendance_logs (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references public.users (id) on delete cascade,
    status     text        not null default 'Hadir',
    method     text,
    timestamp  timestamptz not null default now()
);

alter table public.attendance_logs add column if not exists method text;

alter table public.attendance_logs drop constraint if exists attendance_logs_method_check;
alter table public.attendance_logs
    add constraint attendance_logs_method_check
    check (method is null or method in ('face', 'manual', 'register'));

-- One attendance row per member per WIB day.
--
-- The day must be derived in Asia/Jakarta, not UTC. The service runs Saturday
-- 17:00 WIB; a UTC-based key would place a 06:30 WIB arrival on the previous
-- day and let the same person be recorded twice for one gathering.
--
-- A generated column is used because a UNIQUE constraint cannot take an
-- expression directly in PostgreSQL.
alter table public.attendance_logs
    add column if not exists attendance_date date
    generated always as (((timestamp at time zone 'Asia/Jakarta')::date)) stored;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'unique_user_per_day'
    ) then
        alter table public.attendance_logs
            add constraint unique_user_per_day unique (user_id, attendance_date);
    end if;
exception
    when unique_violation then
        raise warning
            'Duplicate attendance rows exist; deduplicate them, then re-run this migration. '
            'Find them with: select user_id, attendance_date, count(*) '
            'from attendance_logs group by 1, 2 having count(*) > 1;';
end $$;

create index if not exists attendance_logs_user_date_idx
    on public.attendance_logs (user_id, attendance_date desc);
create index if not exists attendance_logs_timestamp_idx
    on public.attendance_logs ("timestamp" desc);

-- ---------------------------------------------------------------------------
-- match_faces
-- ---------------------------------------------------------------------------
-- Cosine distance (<=>), so similarity = 1 - distance and the comparison is
-- scale-invariant: normalised and un-normalised embeddings can coexist while
-- older rows are migrated.
--
-- Archived members are excluded here as well as in the application, so an
-- archived person cannot check in and reappear on the kiosk screen.
create or replace function public.match_faces(
    query_embedding vector(512),
    match_threshold float,
    match_count int
)
returns table (
    id         bigint,
    full_name  text,
    similarity float
)
language sql
stable
as $$
    select
        u.id,
        u.full_name,
        1 - (u.face_embedding <=> query_embedding) as similarity
    from public.users u
    where u.face_embedding is not null
      and u.is_deleted = false
      and 1 - (u.face_embedding <=> query_embedding) >= match_threshold
    order by u.face_embedding <=> query_embedding
    limit match_count;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- The backend holds the key and performs every authorisation check itself, so
-- no PostgREST role needs direct table access. Without this, anyone holding the
-- anon key can bypass the application entirely and read face_embedding for
-- every member.
--
-- IMPORTANT: the backend must use the service_role key, which bypasses RLS.
-- Set SUPABASE_KEY to the service_role key and keep it server-side only —
-- it is never sent to a browser by this application.
alter table public.users          enable row level security;
alter table public.attendance_logs enable row level security;

revoke all on public.users          from anon, authenticated;
revoke all on public.attendance_logs from anon, authenticated;
revoke all on function public.match_faces(vector, float, int) from anon, authenticated;

commit;

-- Verify:
--   select relname, relrowsecurity from pg_class
--    where relname in ('users', 'attendance_logs');   -- both must be true
--   select conname from pg_constraint where conname = 'unique_user_per_day';
